src/Home/Home.jsx, src/Home/OurPartners/OurPartners.jsx, src/Routes/Router.jsx, src/main.jsx, src/pages/Shared/NavBar/NavBar.jsx, src/providers/AuthProvider.jsx
=> Some issu solv

src/pages/Shared/Footer/Footer.jsx
=> footer change

src/Home/FAQ/Faq.jsx, src/Home/Home.jsx, src/pages/Shared/Footer/Footer.jsx
=> faq section added

src/pages/Shared/Footer/Footer.jsx
=> faq section style added

src/Home/FAQ/Faq.jsx
=> faq style added

src/Home/Slider/Slider.jsx
=> Autoplay added on silder

src/Home/Slider/Slider.jsx
=> added responsive on silder

package-lock.json, package.json, src/main.jsx, src/pages/Dashboard/Solve/Solve.jsx, src/pages/Login/Login.jsx, src/pages/Signup/SignUp.jsx, src/pages/Signup/Signup.css, src/providers/AuthProvider.jsx
=> Complit Forget Password

src/pages/Home/Home/Home.jsx
=> banner section fix

src/pages/Shared/Social/SocialLogin.jsx, src/pages/Signup/SignUp.jsx
=> Show toasty messege

src/pages/Home/Banner/Banner.jsx, src/pages/Shared/NavBar/NavBar.jsx
=> some changes of navbar

src/pages/Dashboard/DbUser/DbUser.jsx, src/pages/Dashboard/ProfileEdit/ProfileEdit.jsx, src/pages/Home/FAQ/Faq.jsx
=> faq section responsive

src/pages/Home/Banner/Banner.jsx, src/pages/Shared/NavBar/NavBar.jsx
=> add dropdown

src/Routes/Router.jsx, src/pages/Blog/Blog.jsx, src/pages/Blog/SingleBlog/SingleBlog.jsx, src/pages/Shared/Footer/Footer.jsx
=> Blog page added

src/pages/Home/CodeEditor/CodeEditor.jsx
=> almost done codeeditor with imam vai

src/pages/Shared/Social/SocialLogin.jsx, src/pages/Signup/SignUp.jsx
=> save user info

src/pages/Blog/Blog.jsx, src/pages/Blog/SingleBlog/SingleBlog.jsx
=> fixed some error

src/pages/Problems/ProblemDetails.jsx
almost done problem details page
=> almost done problemDetails page

public/problems.json, src/pages/Problems/ProblemDetails.jsx, src/pages/Problems/Problems.jsx
add some js problem data with testing
=> add jsProblem with testing

src/pages/Home/Banner/Banner.css, src/pages/Subscribe/PaymentFail.jsx, src/pages/Subscribe/PaymentSuccess.jsx
=> desgin payment fail page

package-lock.json, src/pages/CheckOut/CheckOut.jsx, src/pages/Explore/Explore.css, src/pages/Login/Login.jsx, src/pages/Subscribe/Subscribe.jsx
=> subscribe page disign done

src/pages/Problems/Problems.jsx
Filtering system added on problem-solving code
=> Filtering system added on problem solving code

src/Routes/Router.jsx, src/pages/AdminDashbord/AdminDashboard.jsx, src/pages/AdminDashbord/AdminMainContent/AdminMainContent.jsx, src/pages/AdminDashbord/AdminMainContent/OverViewAd/OverViewAd.jsx, src/pages/AdminDashbord/AdminSideBar/AdminSideBar.jsx, src/pages/AdminDashbord/ManageUser/ManageUser.jsx
=> Manage user done

package-lock.json, package.json, src/Routes/Router.jsx, src/layouts/Dashboard.jsx, src/layouts/MainLayout.jsx, src/pages/AdminDashbord/AdminCalendar/AdminCalendar.jsx, src/pages/AdminDashbord/ManageUser/ManageUser.jsx, src/pages/Home/UserCount/UserCount.jsx, src/pages/MySubmissions/MySubmissions.jsx, vite.config.js
=> calender add

src/Routes/Router.jsx
=> explore details route added

src/Routes/PrivateRoute.jsx, src/components/FlexcodeLoading/FlexcodeLoading.jsx, src/pages/MyPlayGround/PlayGround/PlayGround.jsx, src/pages/Problems/ProblemDetails.jsx, src/pages/Subscribe/Subscribe.jsx
=> some changes of overol

src/Hooks/useAllProblems.jsx, src/Hooks/useAllUsers.jsx, src/Hooks/useAuth.jsx, src/Hooks/useAxiosSecure.jsx, src/Hooks/useFlexUser.jsx, src/Hooks/useTopperData.jsx, src/pages/Shared/NavBar/NavBar.css, src/pages/Shared/NavBar/NavBar.jsx
=> navbar responsive done

src/Routes/AdminRoute.jsx, src/Routes/Router.jsx, src/layouts/Dashboard.jsx, src/pages/AdminDashbord/AdminMainContent/AdminMainContent.jsx
=> add admin route

package-lock.json, src/pages/Home/BlogSection/BlogSection.jsx, src/pages/Home/ExploreUs/ExploreUs.jsx, src/pages/Home/Home/Home.jsx
=> all code added

src/pages/Dashboard/NoteBook/NoteBook.jsx
=> verify nodebook route

src/pages/Dashboard/NoteBook/NoteBook.jsx
=> delete single note function

index.html, src/pages/AdminDashbord/AdminDashboard.jsx, src/pages/AdminDashbord/AdminMainContent/AdminMainContent.jsx, src/pages/AdminDashbord/AdminMainContent/OverViewAd/PreUserCard.jsx, src/pages/AdminDashbord/AdminMainContent/UserRatioChart/UserRationChart.jsx, src/pages/Dashboard/NoteBook/NoteBook.jsx, src/pages/MyPlayGround/MyPlayGround.jsx
=> admin dashboard res done

src/pages/Challenge/AllChallenges.jsx
=> add sweetalar
